version: '3'
services:
  web:
    build: ./web
    depends_on:
      - app
    ports:
      - "8081:80"
      - "8080:443"
      - "8082:3031"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/ssl/server.key:/etc/nginx/server.key
      - ./web/ssl/server.key:/etc/nginx/server.crt
      - ./data/html:/var/www/html

  app:
    build: ./app
    volumes:
      - ./app:/var/www/
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
